package org.bloqqi.compiler;

import org.bloqqi.compiler.ast.*;
import org.bloqqi.compiler.ast.BloqqiScanner.ScannerError;
import org.bloqqi.compiler.options.CommandLine;
import org.bloqqi.compiler.options.EnumOption;
import org.bloqqi.compiler.options.FlagOption;
import org.bloqqi.compiler.options.Option;
import org.bloqqi.compiler.options.StringOption;
import org.bloqqi.compiler.options.CommandLine.CommandLineException;

import static org.bloqqi.compiler.Utils.filterToList;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.regex.Pattern;


import beaver.Parser;

public class Compiler {
	protected ArrayList<Option<?>> options;
	protected FlagOption optionPrintAst;
	protected FlagOption optionPrettyPrint;
	protected FlagOption optionFlat;
	protected FlagOption optionFile;
	protected EnumOption optionGenerateC;
	protected FlagOption optionFMI;
	protected StringOption optionDist;
	protected StringOption optionOutputFile;
	protected FlagOption optionDot;
	protected FlagOption optionRec;
	protected FlagOption optionCostEstimates;
	protected StringOption optionFeatureDiagram;
	protected FlagOption optionHelp;
	protected StringOption optionSrcDir;

	protected CommandLine commandLine;
	protected Collection<String> filenames;
	protected Collection<String> types;

	// Enable DrAST debugging
	public static Object DrAST_root_node;

	protected <OptionType extends Option<?>> OptionType addOption(OptionType option) {
		options.add(option);
		return option;
	}

	public Compiler(String args[]) throws CommandLineException {
		options = new ArrayList<>();
		addOptions();

		commandLine = new CommandLine(options);
		parseArguments(args);

		Program program;
		if (filenames.size() > 0) {
			program = parseFiles();
		} else {
			program = parseTypes();
		}
		DrAST_root_node = program;

		printProgramInformation(program);
	}

	protected void addOptions() {
		optionPrintAst = addOption(new FlagOption("ast", "print the AST"));
		optionPrettyPrint = addOption(new FlagOption("pp", "pretty printing"));
		optionFlat = addOption(new FlagOption("flat", "flat pretty printing"));
		optionFile = addOption(new FlagOption("file", "print control builder code to file"));
		optionGenerateC = addOption(
			new EnumOption(
				"c",
				"generate C code",
				Arrays.asList("with-driver", "without-driver", "minimal", "configuration"),
				"with-driver"));
		optionFMI = addOption(new FlagOption("fmi", "generate C for FMI"));
		optionDist = addOption(new StringOption("dist", "specify config and generate C for distributed execution"));
		optionOutputFile = addOption(new StringOption("o", "output file"));
		optionDot = addOption(new FlagOption("dot", "generate DOT visualisation file"));
		optionRec = addOption(new FlagOption("rec", "display recommendations"));
		optionFeatureDiagram = addOption(new StringOption("feature-diagram", "generate feature diagram for diagram type"));
		optionSrcDir = addOption(new StringOption("src", "sets the source directory"));
		optionHelp = addOption(new FlagOption("help", "display usage information and exit"));
		optionCostEstimates = addOption(new FlagOption("cost", "print cost estimates"));
	}

	protected void parseArguments(String[] args) throws CommandLineException {
		if (args.length == 0) {
			showUsageAndExit();
		}

		commandLine.parse(args);

		if (optionOutputFile.isSet()) {
			if (!optionGenerateC.isSet() && !optionFMI.isSet() && !optionDist.isSet()) {
				throw new CommandLineException("Option " + optionOutputFile
					+ " can currently only be set together with option " + optionGenerateC
					+ ", " + optionFMI + ", or " + optionDist);
			} else if (!optionOutputFile.getValue().endsWith(".c")) {
				throw new CommandLineException("The value for option " + optionOutputFile
					+ " should end with the file extension .c");
			}
			try (BufferedReader in = new BufferedReader(new FileReader(optionOutputFile.getValue()))) {
				String firstLine = in.readLine();
				if (firstLine != null && !firstLine.startsWith(ASTNode.GENERATED_C_INFO)) {
					throw new CommandLineException("The file " + optionOutputFile.getValue()
						+ " has not been generated by Bloqqi compiler. Aborting.");
				}
			} catch (IOException e) { /* ignore */ }
		}

		if ((optionFMI.isSet() || optionDist.isSet()) && !optionOutputFile.isSet()) {
			throw new CommandLineException("Output file (" + optionOutputFile
				+ ") needs to be specified when using option " + optionFMI + " or " + optionDist);
		}

		if ((optionFMI.isSet()?1:0) + (optionGenerateC.isSet()?1:0) + (optionDist.isSet()?1:0) > 1) {
			throw new CommandLineException("Only one of the options " + optionFMI
				+ ", " + optionGenerateC + ", " + optionDist + " can be selected.");
		}

		if (optionHelp.isSet() || commandLine.getArguments().isEmpty()) {
			showUsageAndExit();
		}


		filenames = filterToList(commandLine.getArguments(), s -> s.endsWith(".dia"));
		types = filterToList(commandLine.getArguments(), s -> !s.endsWith(".dia"));

		if (filenames.size() > 0 && types.size() > 0) {
			throw new CommandLineException("Cannot specify both types and filenames");
		}
	}

	private Program parseFiles() {
		Program p = new Program();
		p.setStandardLibrary(loadStandardLibrary());
		for (String file: filenames) {
			p.addCompilationUnit(parseFile(file));
		}
		return p;
	}

	private Program parseTypes() throws CommandLineException {
		Program p = new Program();
		p.setStandardLibrary(loadStandardLibrary());

		File srcDir;
		if (optionSrcDir.isSet()) {
			srcDir = new File(optionSrcDir.getValue());
			if (!srcDir.isDirectory()) {
				throw new CommandLineException(optionSrcDir.getValue() + " is not a directory");
			}
		} else {
			srcDir = new File(".");
		}

		Pattern pattern = Pattern.compile("\\w+(\\.\\w+)*");
		for (String type: types) {
			if (!pattern.matcher(type).matches()) {
				throw new CommandLineException("The type \"" + type + "\" is not a valid type name");
			}
			String packageName;
			String typeName;
			if (type.contains(".")) {
				packageName = type.substring(0, type.lastIndexOf("."));
				typeName = type.substring(type.lastIndexOf(".")+1);
			} else {
				packageName = "";
				typeName = type;
			}
			String packagePath = packageName.replace(".", File.separator);
			File packageDir = new File(srcDir, packagePath);
			if (!packageDir.isDirectory()) {
				throw new CommandLineException("The package " + packageName + " does not exist");
			}

			System.out.println(packageName + " -- " + typeName);
			//System.out.println(type.replaceAll("\\.+", File.separator));
		}

		return p;
	}

	protected void printProgramInformation(Program p) {
		if (optionPrintAst.isSet()) {
			p.printAST();
		}
		if (optionPrettyPrint.isSet()) {
			for (CompilationUnit u: p.getCompilationUnits()) {
				System.out.println(u.prettyPrint());
			}
		}
		if (optionFlat.isSet()) {
			for (CompilationUnit u: p.getCompilationUnits()) {
				System.out.println(u.flattenedPrettyPrint());
			}
		}
		if (optionRec.isSet()) {
			printRecommendationsInfo(p);
		}

		if (optionCostEstimates.isSet()) {
			for (CompilationUnit u: p.getCompilationUnits()) {
				System.out.println(u.printCost());
			}
		}

		if (optionFeatureDiagram.isSet()) {
			printAsFeatureDiagram(p);
		}



		boolean errors = false;
		for (CompilationUnit cu: p.getCompilationUnits()) {
			if (!cu.errors().isEmpty()) {
				System.out.println("Errors:");
				for (ErrorMessage e: cu.errors()) {
					System.out.println("- " + e);
				}
				errors = true;
			}
		}
		if (!p.getStandardLibrary().errors().isEmpty()) {
			System.out.println("Errors in standard library:");
			for (ErrorMessage e: p.getStandardLibrary().errors()) {
				System.out.println("- " + e);
			}
			errors = true;
		}

		DistributedCGenerator distC = new DistributedCGenerator(p, optionDist.getValue());
		if (optionDist.isSet()) {
			errors |= !distC.readAndCheckConfig();
		}

		if (!errors && p.getNumCompilationUnit() > 0) {
			if (optionGenerateC.isSet() || optionFMI.isSet() || optionDist.isSet()) {
				if (hasCodeGenerationErrors(p)) {
					System.exit(1);
				} else if (optionGenerateC.isSet()) {
					generateC(p);
				} else if (optionFMI.isSet()) {
					generateCForFMI(p);
				} else if (optionDist.isSet()) {
					distC.generate(optionOutputFile.getValue());
				}
			} else if (optionDot.isSet()) {
				writeToDOT(p, commandLine.getArguments().get(0));
			} else if (printProgramOK()){
				System.out.println("Program OK");
			}
		}

		if (errors) {
			System.exit(1);
		}
	}

	private void printRecommendationsInfo(Program p) {
		for (CompilationUnit u: p.getCompilationUnits()) {
			for (TypeDecl td: u.typeDecls()) {
				if (td.isDiagramType()) {
					DiagramType dt = (DiagramType) td;
					FeatureConfiguration conf = dt.specialize();
					if (conf.hasFeatures()) {
						System.out.println(conf);
					}
				}
			}
		}
	}

	private void printAsFeatureDiagram(Program p) {
		TypeDecl td = p.lookupType(optionFeatureDiagram.getValue());
		if (td == null || !td.isDiagramType()) {
			System.out.println("Diagram type \"" + optionFeatureDiagram.getValue() + "\" could not be found");
		} else {
			DiagramType dt = (DiagramType) td;
			try {
				System.out.println(dt.specialize().asDotDiagram());
			} catch (Exception e) {
				System.out.println("Error! Feature diagram for " + dt.name() + " is recursive.");
				System.exit(1);
			}
		}
	}

	protected boolean printProgramOK() {
		return !optionFlat.isSet()
				&& !optionPrintAst.isSet()
				&& !optionPrettyPrint.isSet()
				&& !optionGenerateC.isSet()
				&& !optionFMI.isSet()
				&& !optionDist.isSet()
				&& !optionFeatureDiagram.isSet();
	}

	protected CodeGenerationTarget getCodeGenerationTarget(Program p) {
		switch (optionGenerateC.getValue()) {
			case "with-driver":
				return new CodeTargetWithDriver(p);
			case "without-driver":
				return new CodeTargetWithoutDriver(p);
			case "minimal":
				return new CodeTargetMinimal(p);
			case "configuration":
				return new CodeTargetConfiguration(p);
		}
		return new CodeTargetWithDriver(p);
	}

	protected CodeGenerationData getCodeGenerationData() {
		if (optionOutputFile.isSet()) {
			String name = new File(optionOutputFile.getValue()).getName();
			name = name.substring(0, name.lastIndexOf('.'));
			return new CodeGenerationData(name);
		} else {
			return new CodeGenerationData();
		}
	}

	protected void generateC(Program p) {
		CodeGenerationTarget target = getCodeGenerationTarget(p);

		if (optionOutputFile.isSet()) {
			File cFile = new File(optionOutputFile.getValue());
			String headerFilename;
			headerFilename = cFile.getName().substring(0, cFile.getName().lastIndexOf('.'));
			headerFilename = headerFilename + ".h";
			File headerFile = new File(cFile.getParent(), headerFilename);

			StringBuilder sbHeader = new StringBuilder();
			StringBuilder sbC = new StringBuilder();
			p.generateCSeparateFiles(headerFilename, sbHeader, sbC, target);
			writeToFile(headerFile, sbHeader.toString());
			writeToFile(cFile, sbC.toString());
		} else {
			System.out.println(p.generateC(target));
		}
	}

	protected void generateCForFMI(Program p) {
		CodeGenerationData data = getCodeGenerationData();

		File cFile = new File(optionOutputFile.getValue());
		writeToFile(cFile, p.generateC(new CodeTargetFMI(p, data)));

		String xmlFilename;
		xmlFilename = cFile.getName().substring(0, cFile.getName().lastIndexOf('.'));
		xmlFilename = xmlFilename + ".xml";
		File xmlFile = new File(cFile.getParent(), xmlFilename);
		StringBuilder sbXml = new StringBuilder();
		p.genXMLForFMI(sbXml, data);
		writeToFile(xmlFile, sbXml.toString());
	}

	private boolean hasCodeGenerationErrors(Program p) {
		boolean errors = false;

		// Configurations don't need a main diagram type
		if (optionGenerateC.getValue().equals("configuration")) {
			if (p.configurations().size() != 1) {
				System.out.println("Error! You need exactly one run configuration when compiling with --c=configuration");
				errors = true;
			}
		} else if (!optionDist.isSet() && !p.mainDiagramErrors().isEmpty()) {
			System.out.println("Code generation errors:");
			for (ErrorMessage e: p.mainDiagramErrors()) {
				System.out.println("- " + e);
			}
			errors = true;
		}
		for (CompilationUnit cu: p.getCompilationUnits()) {
			if (!cu.codeGenerationErrors().isEmpty()) {
				System.out.println("Code generation errors:");
				for (ErrorMessage e: cu.codeGenerationErrors()) {
					System.out.println("- " + e);
				}
				errors = true;
			}
		}
		return errors;
	}

	private CompilationUnit loadStandardLibrary() {
		try {
			return Program.loadStandardLibrary();
		} catch (Exception e) {
			System.err.println("Could not read standard functions");
			System.exit(1);
		}
		return null;
	}

	private CompilationUnit parseFile(String file) {
		FileReader reader = null;
		try {
			reader = new FileReader(file);
		} catch (FileNotFoundException e) {
			System.err.println(e.getMessage());
			System.exit(1);
		}
		return parse(reader, file);
	}

	private CompilationUnit parse(Reader reader, String file) {
		BloqqiScanner scanner = new BloqqiScanner(reader);
		BloqqiParser parser = new BloqqiParser();

		try {
			return (CompilationUnit) parser.parse(scanner);
		} catch (IOException e) {
			System.err.println(e.getMessage());
			System.exit(1);
		} catch (Parser.Exception e) {
			System.err.println("Parse error in file " + file);
			System.err.println(e.getMessage());
			System.exit(1);
		} catch (ScannerError e) {
			System.err.println("Scanner error in file " + file);
			System.err.println(e.getMessage());
			System.exit(1);
		}
		return null;
	}

	private void showUsageAndExit() {
		System.out.println("Usage: java -jar bloqqi-compiler.jar [--option1] [--option2=value] ...  <filename1> [filename2] [filename3] ...");
		System.out.println("Options: ");
		System.out.println(commandLine.printOptionHelp());
		System.exit(1);
	}


	public static void writeToFile(String filename, String str) {
		writeToFile(new File(filename), str);
	}

	public static void writeToFile(File file, String str) {
		FileWriter fw = null;
		try {
			fw = new FileWriter(file);
			fw.write(str);
		} catch (IOException e) {
			e.printStackTrace();
			System.out.println("Aborting.");
			System.exit(1);
		} finally {
			if (fw != null) { try { fw.close(); } catch (Exception e) {} }
		}
	}

	private static void writeToDOT(Program p, String filename) {
		CompilationUnit cu = p.getCompilationUnit(0);
		TypeDecl td = cu.typeDecls().get(0);
		if (td instanceof DiagramType) {
			System.out.println(((DiagramType) td).generateDOT());
		}
	}

	public static void main(String[] args) {
		try {
			new Compiler(args);
		} catch (CommandLineException e) {
			System.out.println(e.getMessage());
			System.exit(1);
		}
	}
}

